local profile added

diff --git a/demo/mvnw b/demo/mvnw
--- a/demo/mvnw
+++ b/demo/mvnw
@@ -105,14 +105,19 @@ trim() {
   printf "%s" "${1}" | tr -d '[:space:]'
 }
 
+case "$0" in
+  */*) MVNW_PROJECTBASEDIR=${0%/*} ;;
+  *) MVNW_PROJECTBASEDIR=. ;;
+esac
+
 # parse distributionUrl and optional distributionSha256Sum, requires .mvn/wrapper/maven-wrapper.properties
 while IFS="=" read -r key value; do
   case "${key-}" in
   distributionUrl) distributionUrl=$(trim "${value-}") ;;
   distributionSha256Sum) distributionSha256Sum=$(trim "${value-}") ;;
   esac
-done <"${0%/*}/.mvn/wrapper/maven-wrapper.properties"
-[ -n "${distributionUrl-}" ] || die "cannot read distributionUrl property in ${0%/*}/.mvn/wrapper/maven-wrapper.properties"
+done <"$MVNW_PROJECTBASEDIR/.mvn/wrapper/maven-wrapper.properties"
+[ -n "${distributionUrl-}" ] || die "cannot read distributionUrl property in $MVNW_PROJECTBASEDIR/.mvn/wrapper/maven-wrapper.properties"
 
 case "${distributionUrl##*/}" in
 maven-mvnd-*bin.*)
